### ISSUE TITLE
403 on https://chatgpt.com/backend-anon/conversation

### ISSUE THREAD

**Issue by aritralegndery** [Mr-Destructive/anonymous-chatgpt#5]
```python
hatgpt --prompt "hello world"
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Infostealer\.venv\Scripts\chatgpt.exe\__main__.py", line 7, in <module>
  File "e:\Infostealer\.venv\lib\site-packages\anonymous_chatgpt\app.py", line 222, in main
    response = chat_prompt(prompt)
  File "e:\Infostealer\.venv\lib\site-packages\anonymous_chatgpt\app.py", line 91, in chat_prompt
    response.raise_for_status()
  File "e:\Infostealer\.venv\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://chatgpt.com/backend-anon/conversation
````

**Comment by MaxwellJK** [comment]
+1 having the same issue...any solution? 🙏

**Comment by eleldev** [comment]
+1

**Comment by eleldev** [comment]
some info about trouble:

```
<Response [403]>
{'error': '{"detail":"Unusual activity has been detected from your device. Try again later. (8d1cee995f3fd279-FRA)"}'}
```

**Comment by eleldev** [comment]
my moded version output:

```
1/2 sub-step passed, sleep (7.822859105165978s) to hide activity
2/2 sub-step successfully passed
1 step passed, sleep (5.562267151657222s) to hide activity
2 step passed, summarizing...


RAW:
<Response [200]>


{'error': '{"type":"conversation_detail_metadata","banner_info":null,"blocked_features":[{"name":"file_upload","resets_after":"2024-10-13T06:04:21.334439+00:00","description":"Upgrade to ChatGPT Plus or try again in 1 minute.","title":null,"block_reason":null,"call_to_action":["authenticate"]}],"model_limits":[],"default_model_slug":"auto"}'}

```

**Comment by eleldev** [comment]
requests structure changed ig..
need to rewrite all

**Comment by MaxwellJK** [comment]
> requests structure changed ig.. need to rewrite all

yeah i also guessed that - the headers are quite different
i tried to work on it but so far no success

**Comment by eleldev** [comment]
> > requests structure changed ig.. need to rewrite all
> 
> yeah i also guessed that - the headers are quite different i tried to work on it but so far no success

maybe we can merge our things and come to smth

**Comment by 11100010** [comment]
same error here:

> Ξ ~ → 423ms chatgpt --chat
user >> hello
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/chatgpt", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anonymous_chatgpt/app.py", line 220, in main
    chat_cli()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anonymous_chatgpt/app.py", line 140, in chat_cli
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://chatgpt.com/backend-anon/conversation


> ↑1 ~ → 5729ms chatgpt --prompt "hello world"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/chatgpt", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anonymous_chatgpt/app.py", line 222, in main
    response = chat_prompt(prompt)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anonymous_chatgpt/app.py", line 91, in chat_prompt
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://chatgpt.com/backend-anon/conversation

**Comment by 0wwafa** [comment]
yep.
$ python3 main.py
Prompt: hello
403 {"detail":"Unusual activity has been detected from your device. Try again later. (9641649f8f197c52-IAD)"}
